# Generated by Django 4.1.5 on 2023-04-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='uuid',
            new_name='id',
        ),
    ]
