# Generated by Django 4.1.5 on 2023-04-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_uuid_class_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('subject', 'catalog_nbr')},
        ),
    ]
