# Generated by Django 4.1.1 on 2023-04-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_classlist_tutor_profile_accepted_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='uuid',
            new_name='id',
        ),
    ]
