# Generated by Django 4.1.7 on 2023-04-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_uuid_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutorsesh',
            name='has_rated',
            field=models.BooleanField(default=False),
        ),
    ]
