from django.db import migrations, transaction
import requests
from mainapp.models import Class

def load_from_api(apps, schema_editor):
    term = '1238'
    # Get the list of department mnemonics
    options_url = f'https://sisuva.admin.virginia.edu/psc/ihprd/UVSS/SA/s/WEBLIB_HCX_CM.H_CLASS_SEARCH.FieldFormula.IScript_ClassSearchOptions?institution=UVA01&term={term}'
    response = requests.get(options_url).json()
    mnemonics = []
    # Render the template with the list of mnemonics
    for s in response['subjects']:
        mnemonics.append(s['subject'])
    classes = {}
    for c in mnemonics:
        s = c.upper()
        url = f'https://sisuva.admin.virginia.edu/psc/ihprd/UVSS/SA/s/WEBLIB_HCX_CM.H_CLASS_SEARCH.FieldFormula.IScript_ClassSearch?institution=UVA01&term={term}'
        response = requests.get(url + '&subject=' + s + '&page=1').json()
        for x in response:
            name = x['subject'] + " " + x['catalog_nbr'] + " " + x['descr']
            classes[name] = True
    url = f'https://sisuva.admin.virginia.edu/psc/ihprd/UVSS/SA/s/WEBLIB_HCX_CM.H_CLASS_SEARCH.FieldFormula.IScript_ClassSearch?institution=UVA01&term={term}'
    courses = []
    for key in classes:
        n = key.split()
        descr = " ".join(n[2:])
        courses.append(Class(subject=n[0], catalog_nbr=n[1], descr=descr))

    with transaction.atomic():
        Class.objects.bulk_create(courses)

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_uuid_class_id'),
    ]

    operations = [
        migrations.RunPython(load_from_api),
    ]
    # Generated by Django 4.1.5 on 2023-04-20 04:45
