# Generated by Django 4.1.5 on 2023-02-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_profile_is_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='is_student'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_tutor',
            field=models.BooleanField(default=False, verbose_name='is_tutor'),
        ),
    ]
