# Generated by Django 4.1.5 on 2023-04-20 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_load_api_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassList',
        ),
    ]
