# Generated by Django 4.1.5 on 2023-03-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_classlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='classes',
            field=models.JSONField(default=[]),
        ),
    ]
