# Generated by Django 4.1.5 on 2023-03-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_profile_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('catalog_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('prereqs', models.TextField(blank=True)),
                ('coreqs', models.TextField(blank=True)),
                ('term', models.CharField(max_length=6)),
                ('meeting_times', models.JSONField(default=list)),
            ],
        ),
    ]
