# Generated by Django 4.1.7 on 2023-03-29 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0009_profile_connected_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='connected_list',
            field=models.ManyToManyField(blank=True, related_name='connected_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
