# Generated by Django 4.1.5 on 2023-03-31 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0010_alter_profile_connected_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accepted_list',
            field=models.ManyToManyField(blank=True, related_name='accepted_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
