# Generated by Django 4.1.7 on 2023-04-05 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0011_profile_accepted_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorSesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_scheduled', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_scheduled', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='schedule_list',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='mainapp.tutorsesh'),
        ),
    ]
