# Generated by Django 3.2.18 on 2023-05-02 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20230502_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fri_avail_end',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mon_avail_end',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sat_avail_end',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sun_avail_end',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='thu_avail_end',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tue_avail_end',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wed_avail_end',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
    ]
