# Generated by Django 4.1.5 on 2023-04-07 19:21
from mainapp.models import Class
from django.db import migrations

def load_classes(apps, schema_editor):
    Class.load_from_api()
class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_load_classes_from_api'),
    ]

    operations = [
    ]

