# Generated by Django 4.1.7 on 2023-04-05 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_profile_schedule_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='schedule_list',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.tutorsesh'),
        ),
    ]
