# Generated by Django 4.1.5 on 2023-04-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_load_classes_from_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('catalog_nbr', models.CharField(max_length=50)),
                ('descr', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
