# Generated by Django 4.1.7 on 2023-04-05 18:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_remove_profile_schedule_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='schedule_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.tutorsesh'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorsesh',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorsesh',
            name='date',
            field=models.DateField(),
        ),
    ]
