# Generated by Django 4.1.7 on 2023-04-05 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_profile_schedule_list_tutorsesh_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='schedule_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.tutorsesh'),
        ),
    ]
