# Generated by Django 4.1.7 on 2023-04-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_profile_schedule_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='schedule_list',
        ),
        migrations.AddField(
            model_name='profile',
            name='schedule_list',
            field=models.ManyToManyField(blank=True, related_name='schedule_list', to='mainapp.tutorsesh'),
        ),
    ]
