# Generated by Django 4.1.7 on 2023-04-06 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0019_remove_profile_schedule_list_profile_schedule_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorsesh',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scheduled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorsesh',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_scheduled', to=settings.AUTH_USER_MODEL),
        ),
    ]
