# Generated by Django 4.1.5 on 2023-04-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_class_delete_course'),
        ('mainapp', '0020_alter_tutorsesh_student_alter_tutorsesh_tutor'),
    ]

    operations = [
    ]
