# Generated by Django 4.1.5 on 2023-04-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_merge_20230410_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='schedule_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='schedule_list', to='mainapp.tutorsesh'),
        ),
    ]
