# Generated by Django 4.1.5 on 2023-04-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_alter_profile_schedule_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='schedule_list',
            field=models.ManyToManyField(blank=True, related_name='schedule_list', to='mainapp.tutorsesh'),
        ),
    ]
