# Generated by Django 4.1.5 on 2023-04-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_class_tutors_remove_profile_classes_profile_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
