# Generated by Django 4.1.5 on 2023-04-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_alter_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='classes',
        ),
        migrations.AddField(
            model_name='profile',
            name='classes',
            field=models.JSONField(default=[]),
        ),
    ]
