# Generated by Django 4.1.5 on 2023-04-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_remove_profile_classes_profile_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='classes',
        ),
        migrations.AddField(
            model_name='profile',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='classes', to='mainapp.class'),
        ),
    ]
