# Generated by Django 4.1.7 on 2023-04-12 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_remove_profile_classes_profile_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avail_end',
            field=models.TimeField(default=datetime.time(23, 59, 59)),
        ),
        migrations.AddField(
            model_name='profile',
            name='avail_start',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='profile',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
