# Generated by Django 4.1.5 on 2023-04-17 19:11

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0029_tutor_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='tutors',
            field=models.ManyToManyField(blank=True, default=[], related_name='tutors', to=settings.AUTH_USER_MODEL),
        ),
    ]
