# Generated by Django 4.1.7 on 2023-04-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_profile_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
