# Generated by Django 4.1.5 on 2023-04-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_alter_class_id_alter_class_tutors'),
        ('mainapp', '0031_alter_profile_hourly_rate'),
    ]

    operations = [
    ]
